<?php

/**
 * Custom rewrites for Guides CPT and Guide Topics taxonomy
 * Add this code to your theme's functions.php file or a custom plugin
 */

function custom_guide_rewrites() {
    // Base slug for guides
    $guide_base = 'therapy-basics';
    
    // 1. Guide CPT archive: domain.com/therapy-basics/
    // This should work automatically with your has_archive setting, but we can ensure it
    add_rewrite_rule(
        '^' . $guide_base . '/?$',
        'index.php?post_type=guide',
        'top'
    );
    
    // 2. Guide topic taxonomy archive: domain.com/therapy-basics/{guide-topic-slug}/
    add_rewrite_rule(
        '^' . $guide_base . '/([^/]+)/?$',
        'index.php?guide-topic=$matches[1]',
        'top'
    );
    
    // 3. Single guide with topic: domain.com/therapy-basics/{guide-topic-slug}/{guide-post-slug}
    add_rewrite_rule(
        '^' . $guide_base . '/([^/]+)/([^/]+)/?$',
        'index.php?guide-topic=$matches[1]&guide=$matches[2]',
        'top'
    );
    
    // 4. Pagination for guide topic archives
    add_rewrite_rule(
        '^' . $guide_base . '/([^/]+)/page/([0-9]{1,})/?$',
        'index.php?guide-topic=$matches[1]&paged=$matches[2]',
        'top'
    );
    
    // 5. Pagination for main guide archive
    add_rewrite_rule(
        '^' . $guide_base . '/page/([0-9]{1,})/?$',
        'index.php?post_type=guide&paged=$matches[1]',
        'top'
    );
    
    // Note: Individual guide pagination is disabled in ACF config (pages: "0")
    // Archive pagination above is still needed for guide listings
}
add_action('init', 'custom_guide_rewrites');

/**
 * Modify the permalink structure for guide posts
 * This ensures links generated by WordPress follow our custom structure
 */
function custom_guide_permalink($permalink, $post) {
    if ($post->post_type !== 'guide') {
        return $permalink;
    }
    
    // Get the guide topics for this post
    $terms = wp_get_post_terms($post->ID, 'guide-topic');
    
    if (!empty($terms) && !is_wp_error($terms)) {
        // Use the first topic if multiple exist
        $topic_slug = $terms[0]->slug;
        return home_url("/therapy-basics/{$topic_slug}/{$post->post_name}/");
    } else {
        // Fallback if no topic is assigned - you might want to handle this differently
        return home_url("/therapy-basics/uncategorized/{$post->post_name}/");
    }
}
add_filter('post_type_link', 'custom_guide_permalink', 10, 2);

/**
 * Modify the term link for guide topics
 * This ensures taxonomy archive links follow our custom structure
 */
function custom_guide_topic_link($link, $term, $taxonomy) {
    if ($taxonomy !== 'guide-topic') {
        return $link;
    }
    
    return home_url("/therapy-basics/{$term->slug}/");
}
add_filter('term_link', 'custom_guide_topic_link', 10, 3);

/**
 * Handle query vars for our custom structure
 * This ensures WordPress recognizes our custom URL parameters
 */
function custom_guide_query_vars($vars) {
    $vars[] = 'guide';
    $vars[] = 'guide-topic';
    return $vars;
}
add_filter('query_vars', 'custom_guide_query_vars');

/**
 * Parse the request and set up proper query
 * This handles the logic for determining what content to show
 */
function custom_guide_parse_request($wp) {
    // Check if we're dealing with guide-related queries
    if (!isset($wp->query_vars['guide-topic']) && !isset($wp->query_vars['guide'])) {
        return;
    }
    
    // Single guide post
    if (isset($wp->query_vars['guide-topic']) && isset($wp->query_vars['guide'])) {
        $guide_slug = $wp->query_vars['guide'];
        $topic_slug = $wp->query_vars['guide-topic'];
        
        // Find the guide post
        $guide_query = new WP_Query(array(
            'post_type' => 'guide',
            'name' => $guide_slug,
            'posts_per_page' => 1
        ));
        
        if ($guide_query->have_posts()) {
            $post = $guide_query->posts[0];
            
            // Verify this post has the correct topic
            $post_terms = wp_get_post_terms($post->ID, 'guide-topic');
            $has_topic = false;
            
            foreach ($post_terms as $term) {
                if ($term->slug === $topic_slug) {
                    $has_topic = true;
                    break;
                }
            }
            
            if ($has_topic) {
                // Set up single post query
                $wp->query_vars['post_type'] = 'guide';
                $wp->query_vars['name'] = $guide_slug;
                unset($wp->query_vars['guide']);
                unset($wp->query_vars['guide-topic']);
            } else {
                // Topic doesn't match - show 404
                $wp->query_vars['error'] = '404';
            }
        } else {
            // Post not found
            $wp->query_vars['error'] = '404';
        }
    }
    // Guide topic archive
    elseif (isset($wp->query_vars['guide-topic']) && !isset($wp->query_vars['guide'])) {
        $topic_slug = $wp->query_vars['guide-topic'];
        
        // Verify the topic exists
        $term = get_term_by('slug', $topic_slug, 'guide-topic');
        
        if ($term) {
            // Set up taxonomy archive query
            $wp->query_vars['taxonomy'] = 'guide-topic';
            $wp->query_vars['term'] = $topic_slug;
            unset($wp->query_vars['guide-topic']);
        } else {
            // Topic not found
            $wp->query_vars['error'] = '404';
        }
    }
}
add_action('parse_request', 'custom_guide_parse_request');

/**
 * Flush rewrite rules on theme activation
 * Add this to ensure rules are registered properly
 */
function flush_guide_rewrites() {
    custom_guide_rewrites();
    flush_rewrite_rules();
}
add_action('after_switch_theme', 'flush_guide_rewrites');

/**
 * Optional: Add a function to manually flush rewrites
 * You can call this function or visit wp-admin and go to Settings > Permalinks to flush
 */
function manual_flush_guide_rewrites() {
    if (current_user_can('manage_options')) {
        flush_rewrite_rules();
    }
}
// Uncomment the line below if you want to flush on every admin page load (remove after testing)
// add_action('admin_init', 'manual_flush_guide_rewrites');
