name: Deploy to Staging (Pre-production)
run-name: Deploy to Staging (Pre-production) on ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Staging (Pre-prod)"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Staging (Pre-production)
        uses: ./.github/actions/deploy
        with:
          branch: "staging"
          server_ip: ${{ secrets.KINSTA_SERVER_IP }}
          username: ${{ secrets.KINSTA_USERNAME }}
          password: ${{ secrets.KINSTA_PASSWORD }}
          port: ${{ secrets.KINSTA_PORT }}
