name: Deploy to Staging (Pre-production)
run-name: Deploy to Staging (Pre-production) on ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "Staging (Pre-production)"
      branch: "staging"
      environment_name: "Staging (Pre-prod)"
    secrets:
      KINSTA_SERVER_IP: ${{ secrets.KINSTA_SERVER_IP }}
      KINSTA_USERNAME: ${{ secrets.KINSTA_USERNAME }}
      KINSTA_PASSWORD: ${{ secrets.KINSTA_PASSWORD }}
      KINSTA_PORT: ${{ secrets.KINSTA_PORT }}
